# Multiple value devices
temperatur_terrasse:
  name: Temperatur Terrasse
  entities: 
    - sensor.temp_terrasse_actual_temperature
    - sensor.temp_terrasse_humidity

temperatur_fluegel:
  name: Temperatur Flügel
  entities:
    - sensor.klima_flugel_humidity
    - sensor.klima_flugel_humidity

temperatur_schreibtisch:
  name: Temperatur Schreibtisch
  entities:
    - sensor.temp_schreibtisch_actual_temperature
    - sensor.temp_schreibtisch_humidity

temperatur_reduit:
  name: Temperatur Reduit
  entities:
    - sensor.temp_reduit_actual_temperature
    - sensor.temp_reduit_humidity

temperatur_bad:
  name: Temperatur Bad
  entities:
    - sensor.temp_bad_actual_temperature
    - sensor.temp_bad_humidity

temperatur_garten:
  name: Temperatur Garten
  entities:
    - sensor.heizung_schlafzimmer_actual_temperature
    - sensor.klima_garten_humidity
    - sensor.klima_garten_wind_speed
    - sensor.klima_garten_illumination
    - sensor.klima_garten_sunshineduration

temperatur_schlafzimmer:
  name: Temperatur Schlafzimmer
  entities:
    - sensor.heizung_schlafzimmer_actual_temperature
    - sensor.heizung_schlafzimmer_humidity

temperatur_flur:
  name: Temperatur Flur
  entities:
    - sensor.heizung_wohnzimmer_actual_temperature
    - sensor.heizung_wohnzimmer_humidity


strom_schreibtisch:
  name: Strom Schreibtisch
  entities:
    - sensor.strom_schreibtisch_power
    - sensor.strom_schreibtisch_energy_counter
    - sensor.strom_schreibtisch_current
    - sensor.strom_schreibtisch_voltage
    - sensor.strom_schreibtisch_frequency

strom_brunnen:
  name: Strom Brunnen
  entities:
    - sensor.meq1478516_power
    - sensor.meq1478516_energy_counter
    - sensor.meq1478516_current
    - sensor.meq1478516_voltage
    - sensor.meq1478516_frequency

strom_flur:
  name: Strom Flurlicht
  entities:
    - sensor.licht_gang_power
    - sensor.licht_gang_energy_counter
    - sensor.licht_gang_current
    - sensor.licht_gang_voltage
    - sensor.licht_gang_frequency

strom_wohnzimmer:
  name: Strom Wohnzimmer Sofa
  entities:
    - sensor.strom_sofa_power
    - sensor.strom_sofa_energy_counter
    - sensor.strom_sofa_current
    - sensor.strom_sofa_voltage
    - sensor.strom_sofa_frequency

strom_kueche:
  name: Strom Küchenlicht
  entities:
    - sensor.licht_kueche_power
    - sensor.licht_kueche_energy_counter
    - sensor.licht_kueche_current
    - sensor.licht_kueche_voltage
    - sensor.licht_kueche_frequency

schalter_brunnen:
  name: Schalter Brunnen
  entities:
    - switch.meq1478516

schalter_schreibtisch:
  name: Schalter Schreibtisch
  entities:
    - switch.strom_schreibtisch

schalter:
  name: Schalter
  entities:
    - group.schalter_brunnen
    - group.schalter_schreibtisch

bewegung:
  name: Bewegungsmelder
  entities:
    - binary_sensor.bewegung_wohnzimmer_motion

# Automatisierungen
notify_brunnen:
  name: Brunnen
  entities:
    - automation.brunnen_bei_feuchter_luft
    - automation.brunnen_bei_trockener_luft

notify_fenster:
  name: Fenster/Türen
  entities:
    - automation.meldung_kuchenfenster_offen
    - automation.meldung_schlafzimmerfenster_offen
    - automation.meldung_turen_offen

notifications:
  name: Notifications
  entities:
    - group.notify_fenster
    - group.notify_brunnen

#
################## TABS ##################

#default_view:
home:
  name: Home
#  view: true
  entities:
    - group.licht
    - group.schalter

klima:
  name: Klima
#  view: true
  entities:
    - group.temperatur_terrasse
    - group.temperatur_fluegel
    - group.temperatur_schlafzimmer
    - group.temperatur_reduit
    - group.temperatur_bad
    - group.temperatur_schreibtisch
    - group.temperatur_garten
    - group.temperatur_flur

sicherheit:
  name: Sicherheit
#  view: true
  entities:
    - binary_sensor.tueren
    - binary_sensor.fenster
    - group.bewegung

Verbrauch:
  name: Verbrauch
#  view: true
  entities:
    - group.strom_brunnen
    - group.strom_schreibtisch

automation:
  name: Automation
#  view: true
  entities:
    - group.all_automations
