# Multiple value devices
temperatur_terrasse:
  name: Temperatur Terrasse
  entities: 
    - sensor.000ed8a9909c6d_actual_temperature
    - sensor.000ed8a9909c6d_humidity

temperatur_fluegel:
  name: Temperatur Fl端gel
  entities:
    - sensor.000ed8a9909c6f_actual_temperature
    - sensor.000ed8a9909c6f_humidity

temperatur_schreibtisch:
  name: Temperatur Schreibtisch
  entities:
    - sensor.000ed8a9909c8e_actual_temperature
    - sensor.000ed8a9909c8e_humidity

temperatur_reduit:
  name: Temperatur Reduit
  entities:
    - sensor.000ed8a9909e0e_actual_temperature
    - sensor.000ed8a9909e0e_humidity

temperatur_bad:
  name: Temperatur Bad
  entities:
    - sensor.000ed8a9909c09_actual_temperature
    - sensor.000ed8a9909c09_humidity

temperatur_garten:
  name: Temperatur Garten
  entities:
    - sensor.0017d709ae2f48_actual_temperature
    - sensor.0017d709ae2f48_humidity
    - sensor.0017d709ae2f48_wind_speed
    - sensor.0017d709ae2f48_illumination
    - sensor.0017d709ae2f48_sunshineduration

temperatur_schlafzimmer:
  name: Temperatur Schlafzimmer
  entities:
    - sensor.000c98a99501f3_actual_temperature
    - sensor.000c98a99501f3_humidity

temperatur_flur:
  name: Temperatur Flur
  entities:
    - sensor.000c98a99501c4_actual_temperature
    - sensor.000c98a99501c4_humidity


strom_schreibtisch:
  name: Strom Schreibtisch
  entities:
    - sensor.001015699eacfa_power
    - sensor.001015699eacfa_energy_counter
    - sensor.001015699eacfa_current
    - sensor.001015699eacfa_voltage
    - sensor.001015699eacfa_frequency

strom_brunnen:
  name: Strom Brunnen
  entities:
    - sensor.hmespmsw1pldnr5_meq1478516_power
    - sensor.hmespmsw1pldnr5_meq1478516_energy_counter
    - sensor.hmespmsw1pldnr5_meq1478516_current
    - sensor.hmespmsw1pldnr5_meq1478516_voltage
    - sensor.hmespmsw1pldnr5_meq1478516_frequency

strom_flur:
  name: Strom Flurlicht
  entities:
    - sensor.000898a9951e58_power
    - sensor.000898a9951e58_energy_counter
    - sensor.000898a9951e58_current
    - sensor.000898a9951e58_voltage
    - sensor.000898a9951e58_frequency

strom_wohnzimmer:
  name: Strom Wohnzimmer Sofa
  entities:
    - sensor.000898a9951a7c_power
    - sensor.000898a9951a7c_energy_counter
    - sensor.000898a9951a7c_current
    - sensor.000898a9951a7c_voltage
    - sensor.000898a9951a7c_frequency

strom_kueche:
  name: Strom K端chenlicht
  entities:
    - sensor.000898a9932fdf_power
    - sensor.000898a9932fdf_energy_counter
    - sensor.000898a9932fdf_current
    - sensor.000898a9932fdf_voltage
    - sensor.000898a9932fdf_frequency

schalter_brunnen:
  name: Schalter Brunnen
  entities:
    - switch.hmespmsw1pldnr5_meq1478516

schalter_schreibtisch:
  name: Schalter Schreibtisch
  entities:
    - switch.001015699eacfa

# Group of devices
fenster:
  name: Fenster
  entities:
    - binary_sensor.0000d8a991d301_state
    - binary_sensor.0000d8a991d331_state

tueren:
  name: T端ren
  entities:
    - binary_sensor.0000d8a991d35c_state
    - binary_sensor.0000d8a991d263_state

licht:
  name: Licht
  entities:
    - light.wohnzimmer_licht
    - light.schlafzimmer
    - light.hue_lightstrip_plus_1
    - switch.000898a9951e58
    - switch.000898a9932fdf

schalter:
  name: Schalter
  entities:
    - group.schalter_brunnen
    - group.schalter_schreibtisch

bewegung:
  name: Bewegungsmelder
  entities:
    - binary_sensor.000915699a427d_motion

# Automatisierungen
notify_brunnen:
  name: Brunnen
  entities:
    - automation.brunnen_bei_feuchter_luft
    - automation.brunnen_bei_trockener_luft

notify_fenster:
  name: Fenster/T端ren
  entities:
    - automation.meldung_kuchenfenster_offen
    - automation.meldung_schlafzimmerfenster_offen
    - automation.meldung_turen_offen

notifications:
  name: Notifications
  entities:
    - group.notify_fenster
    - group.notify_brunnen

#
################## TABS ##################

#default_view:
home:
  name: Home
  view: true
  entities:
    - group.licht
    - group.schalter

klima:
  name: Klima
  view: true
  entities:
    - group.temperatur_terrasse
    - group.temperatur_fluegel
    - group.temperatur_schlafzimmer
    - group.temperatur_reduit
    - group.temperatur_bad
    - group.temperatur_schreibtisch
    - group.temperatur_garten
    - group.temperatur_flur

sicherheit:
  name: Sicherheit
  view: true
  entities:
    - group.tueren
    - group.fenster
    - group.bewegung

Verbrauch:
  name: Verbrauch
  view: true
  entities:
    - group.strom_brunnen
    - group.strom_schreibtisch

automation:
  name: Automation
  view: true
  entities:
    - group.all_automations

