resources:
  - url: /local/plan-coordinates.js?v=1
    type: js
  - url: /local/card-group.js
    type: js
  - url: /local/state-attribute-element.js
    type: js
  - url: /local/thermostat-card.js
    type: module

title: Seehaus
views:
  - icon: mdi:home-assistant
    id: home
    title: Home
    cards:
     # - type: custom:plan-coordinates
      - id: a084d8c80a7b445bad3bd7d4c7d56257  # Automatically created id
        type: picture-elements
        image: /local/floorplan2.png
        elements:
          ########## FENSTER/TUEREN ##############
          #Haustür
          - type: state-icon
            entity: binary_sensor.0000d8a991d35c_state
            style:
              left: 13%
              top: 5%
          #Schlafzimmerfenster
          - type: state-icon
            entity: binary_sensor.0000d8a991d331_state
            style:
              left: 75%
              top: 13%
          #Küchenfenster
          - type: state-icon
            entity: binary_sensor.0000d8a991d301_state
            style:
              left: 85%
              top: 48%
          #Terrassentür
          - type: state-icon
            entity: binary_sensor.0000d8a991d263_state
            style:
              left: 28%
              top: 98%
          ########## Lichter ##############
          - type: state-icon
            entity: light.hue_lightstrip_plus_1
            tap_action:
              action: toggle
            hold_action:
              action: more-info
            style:
              left: 8%
              top: 80%
          - type: state-icon
            entity: light.wohnzimmer_licht
            tap_action:
              action: toggle
            hold_action:
              action: more-info
            style:
              left: 70%
              top: 72%
          - type: state-icon
            entity: light.schlafzimmer
            tap_action:
              action: toggle
            hold_action:
              action: more-info
            style:
              left: 71%
              top: 22%
          - type: state-icon
            entity: switch.000898a9932fdf
            tap_action:
              action: toggle
            hold_action:
              action: more-info
            style:
              left: 68%
              top: 48%
          - type: state-icon
            entity: switch.000898a9951e58
            tap_action:
              action: toggle
            hold_action:
              action: more-info
            style:
              left: 35%
              top: 31%
          ########## Schalter ##############
          # Schreibtisch
          - type: state-icon
            entity: switch.001015699eacfa
            tap_action:
              action: toggle
            style:
              left: 55%
              top: 90%
          # Sofa
          - type: state-icon
            entity: switch.000898a9951a7c
            tap_action:
              action: toggle
            style:
              left: 8%
              top: 65%
          ########## Temperatur/Luftfeuchte ##############
          # Wohnzimmer 1
          - type: state-label
            entity: sensor.000ed8a9909c6f_actual_temperature
            tap_action:
              action: none
            style:
              text-align: center
              font-size: 18px
              color: red
              font-family: Helvetica
              left: 55%
              top: 65%
          - type: state-label
            entity: sensor.000ed8a9909c6f_humidity
            tap_action:
              action: none
            style:
              text-align: center
              font-size: 18px
              color: red
              font-family: Helvetica
              left: 55%
              top: 68%
          # Wohnzimmer 2
          - type: state-label
            entity: sensor.000ed8a9909c8e_actual_temperature
            tap_action:
              action: none
            style:
              text-align: center
              font-size: 18px
              color: red
              font-family: Helvetica
              left: 45%
              top: 90%
          - type: state-label
            entity: sensor.000ed8a9909c8e_humidity
            tap_action:
              action: none
            style:
              text-align: center
              font-size: 18px
              color: red
              font-family: Helvetica
              left: 45%
              top: 93%
          # Wohnzimmer Thermostat
          - type: custom:state-attribute-element
            entity: climate.000c98a99501c4
            attribute: current_temperature
            suffix: "°C"
            tap_action:
              action: none
            style:
              text-align: center
              font-size: 18px
              color: red
              font-family: Helvetica
              left: 39%
              top: 40%
          - type: custom:state-attribute-element
            entity: climate.000c98a99501c4
            attribute: current_humidity
            suffix: "%"
            tap_action:
              action: none
            style:
              text-align: center
              font-size: 18px
              color: red
              font-family: Helvetica
              left: 40%
              top: 43%
          # Schlafzimmer Thermostat
          - type: custom:state-attribute-element
            entity: climate.000c98a99501f3
            attribute: current_temperature
            suffix: "°C"
            tap_action:
              action: none
            style:
              text-align: center
              font-size: 18px
              color: red
              font-family: Helvetica
              left: 55%
              top: 22%
          - type: custom:state-attribute-element
            entity: climate.000c98a99501f3
            attribute: current_humidity
            suffix: "%"
            tap_action:
              action: none
            style:
              text-align: center
              font-size: 18px
              color: red
              font-family: Helvetica
              left: 55%
              top: 25%
          # Reduit
          - type: state-label
            entity: sensor.000ed8a9909e0e_actual_temperature
            tap_action:
              action: none
            style:
              text-align: center
              font-size: 14px
              color: red
              font-family: Helvetica
              left: 15%
              top: 46%
          - type: state-label
            entity: sensor.000ed8a9909e0e_humidity
            tap_action:
              action: none
            style:
              text-align: center
              font-size: 14px
              color: red
              font-family: Helvetica
              left: 15%
              top: 49%
          # Bad
          - type: state-label
            entity: sensor.000ed8a9909c09_actual_temperature
            tap_action:
              action: none
            style:
              text-align: center
              font-size: 14px
              color: red
              font-family: Helvetica
              left: 15%
              top: 20%
          - type: state-label
            entity: sensor.000ed8a9909c09_humidity
            tap_action:
              action: none
            style:
              text-align: center
              font-size: 14px
              color: red
              font-family: Helvetica
              left: 15%
              top: 23%
          ####### Storen #######
          - type: icon
            entity: cover.schlafzimmer_links
            icon: mdi:window-closed
            style:
              left: 91%
              top: 11%
          - type: icon
            entity: cover.schlafzimmer_rechts
            icon: mdi:window-closed
            style:
              left: 96%
              top: 20%
          - type: icon
            entity: cover.storen_kueche_links
            icon: mdi:window-closed
            style:
              left: 95%
              top: 48%
          - type: icon
            entity: cover.storen_kueche_rechts
            icon: mdi:window-closed
            style:
              left: 95%
              top: 67%
          - type: icon
            entity: cover.storen_wohnzimmer_links
            icon: mdi:window-closed
            style:
              left: 95%
              top: 83%
          - type: icon
            entity: cover.storen_wohnzimmer_rechts
            icon: mdi:window-closed
            style:
              left: 86%
              top: 93%
          - type: icon
            entity: cover.storen_terrasse_links
            icon: mdi:window-closed
            style:
              left: 58%
              top: 98%
          - type: icon
            entity: cover.storen_terrasse_rechts
            icon: mdi:window-closed
            style:
              left: 20%
              top: 98%
          - type: icon
            entity: vacuum.gollum
            icon: mdi:robot-vacuum
            style:
              left: 10%
              top: 10%
  - icon: mdi:remote
    id: control
    title: Überblick
    cards:
      - type: sensor
        entity: sensor.000ed8a9909c6d_actual_temperature
        name: Aussentemperatur (Terrasse)
        graph: line
        unit: °C
        detail: 6
      - type: sensor
        entity: sensor.0017d709ae2f48_actual_temperature
        name: Aussentemperatur (Garten)
        graph: line
        unit: °C
        detail: 6
      - type: sensor
        entity: sensor.0017d709ae2f48_humidity
        name: Luftfeuchtigkeit Garten
        graph: line
        unit: '%'
        detail: 6
      - type: sensor
        entity: sensor.0017d709ae2f48_wind_speed
        name: Windgeschwindigkeit
        graph: line
        unit: km/h
        detail: 6
      - id: 7c3ad8c3259f401bb3552dcb4adf5cf6  # Automatically created id
        type: entities
        titel: Storen
        entities:
          - cover.wohnzimmer
          - cover.schlafzimmer
          - input_datetime.storen_halb_oeffnen
          - input_datetime.storen_ganz_oeffnen

      - type: entities
        title: Schalter
        entities:
          - switch.hmespmsw1pldnr5_meq1478516
          - switch.001015699eacfa
          - switch.000898a9951a7c
          - switch.001015699eaa6b
      - type: horizontal-stack
        cards:
          - type: thermostat
            name: Schlafzimmer
            entity: climate.000c98a99501f3
          - type: thermostat
            name: Wohnzimmer
            entity: climate.000c98a99501c4
      - type: history-graph
        title: Heizung
        hours_to_show: 6
        entities:
          - binary_sensor.000c98a99501c4_state
          - binary_sensor.000c98a99501f3_state
  - icon: mdi:cctv
    id: security
    title: Sicherheit
    cards:
      - id: 3349c36a202d46cd85e867774c33418f  # Automatically created id
        type: picture-glance
        title: Wohnzimmer
        camera_image: camera.sauron
        entities:
          - switch.hmespmsw1pldnr5_meq1478516
          - switch.001015699eacfa
          - binary_sensor.000915699a427d_motion
          - binary_sensor.0000d8a9aaa854_state
      - type: picture-glance
        title: Flügel
        camera_image: camera.amon_sul
        entities:
          - binary_sensor.000915699a427d_motion
      - type: entities
        title: Notifications
        show_header_toggle: false
        entities:
          - group.notify_fenster
          - group.notify_brunnen
      - type: entities
        title: WLAN
        show_header_toggle: false
        entities:
          - device_tracker.iphonexr
          - device_tracker.lalaith
  - icon: mdi:robot
    id: automations
    title: Automatisierungen
    cards:
      - id: 2d6c5bcc4c2a47fc8642ed0907e9391f  # Automatically created id
        type: "custom:group-card"
        title: Automatisierungen
        group: group.all_automations
  - icon: mdi:robot-vacuum
    id: vacuum
    title: Staubsauger
    cards:
      - type: picture-glance
        title: Gollum
        camera_image: camera.roomba
        entities:
          - vacuum.gollum
  - icon: mdi:flash
    id: verbrauch
    title: Verbrauch
    cards:
      - id: b5e61d2ac54c49d7af332f17c1536d35  # Automatically created id
        type: "custom:group-card"
        title: Brunnen
        group: group.strom_brunnen
      - id: 8fc16df9aa2649218c8066e531e4a8e4  # Automatically created id
        type: "custom:group-card"
        title: PC
        group: group.strom_schreibtisch
      - id: c9c17fad4bb747eabdd50e137d3d96dc  # Automatically created id
        type: "custom:group-card"
        title: Flur
        group: group.strom_flur
      - id: cec2a3e83af244688ab2e10ed1b912e7  # Automatically created id
        type: "custom:group-card"
        title: Küche
        group: group.strom_kueche
      - id: df1eccc669774abcb1bec515baa59c56  # Automatically created id
        type: "custom:group-card"
        title: Wohnzimmer
        group: group.strom_wohnzimmer
  - icon: mdi:flower
    id: garten
    title: Garten
    cards:
      - type: plant-status
        entity: plant.thuja
      - type: plant-status
        entity: plant.lavendel
      - type: picture-glance
          title: Radagast
          camera_image: camera.radagast
