- alias: 'Storen abends schliessen'
  id: storen_abends
  trigger:
    platform: time_pattern
    minutes: '/10'
  condition:
    condition: and
    conditions:
      - condition: or
        conditions:
          - condition: state
            entity_id: cover.schlafzimmer
            state: 'open'
          - condition: state
            entity_id: cover.wohnzimmer
            state: 'open'
      - condition: or
        conditions:
          - condition: sun
            after: sunset
            after_offset: '+00:15:00'
          - condition: time
            after: '21:30:00'
  action:
    - delay:
        minutes: "{{ range(0,9) | random | int }}"
        seconds: "{{ range(0,59) | random | int }}"
    - service: cover.set_cover_tilt_position
      data:
        entity_id: cover.schlafzimmer
        tilt_position: 9
    - service: cover.set_cover_tilt_position
      data:
        entity_id: cover.wohnzimmer
        tilt_position: 9
    - delay:
        seconds: 5
    - service: cover.close_cover
      entity_id: cover.schlafzimmer, cover.wohnzimmer
    - service: automation.turn_off
      entity_id: automation.storen_abends_schliessen
