- alias: 'Storen: Morgens halb öffnen'
  id: storen_halb_oeffnen
  trigger:
    platform: template
    value_template: "{{ states.sensor.time.state ==  (states.input_datetime.storen_halb_oeffnen.attributes.timestamp | int | timestamp_custom('%h:%m', false))}}"
  action:
    - delay:
        minutes: "{{ range(0,10) | random | int }}"
        seconds: "{{ range(0,59) | random | int }}"
    - service: cover.open_cover_tilt
      entity_id: cover.schlafzimmer, cover.wohnzimmer

- alias: 'Storen: Morgens ganz öffnen'
  id: storen_ganz_oeffnen
  trigger:
    platform: template
    value_template:  "{{ states.sensor.time.state == (states.input_datetime.storen_ganz_oeffnen.attributes.timestamp | int | timestamp_custom('%h:%m', false))}}"
  action:
    - delay:
        minutes: "{{ range(0,10) | random | int }}"
        seconds: "{{ range(0,59) | random | int }}"
    - service: cover.open_cover_tilt
      entity_id: cover.schlafzimmer, cover.wohnzimmer
    - delay:
        seconds: 10
    - service: cover.open_cover
      entity_id: cover.schlafzimmer, cover.wohnzimmer
    - service: automation.turn_on
      entity_id: automation.storen_abends_schliessen
