- alias: 'Storen Wohnzimmer bei Sonne halb schliessen'
  id: storen_bei_sonne_zu
  trigger:
    platform: numeric_state
    entity_id: sensor.0017d709ae2f48_illumination
    above: 10000
    for:
      minutes: 5
  action:
    - condition: and
      conditions:
        - condition: and
          conditions:
            - condition: numeric_state
              entity_id: 'sensor.000ed8a9909c6d_actual_temperature'
              above: 20
            - condition: numeric_state
              entity_id: 'sensor.0017d709ae2f48_illumination'
              above: 8000
        - condition: or
          conditions:
            - condition: template
              value_template: '{{ states.cover.storen_terrasse_links.attributes.current_position > 75 }}'
            - condition: template
              value_template: '{{ states.cover.storen_terrasse_rechts.attributes.current_position > 75 }}'
            - condition: template
              value_template: '{{ states.cover.storen_wohnzimmer_rechts.attributes.current_position > 75 }}'
            - condition: template
              value_template: '{{ states.cover.storen_wohnzimmer_links.attributes.current_position > 75 }}'
            - condition: template
              value_template: '{{ states.cover.storen_kueche_rechts.attributes.current_position > 75 }}'
            - condition: template
              value_template: '{{ states.cover.storen_kueche_links.attributes.current_position > 75 }}'
    - service: cover.set_cover_position
      data:
        entity_id: cover.storen_terrasse_links
        position: 60
    - service: cover.set_cover_position
      data:
        entity_id: cover.storen_terrasse_rechts
        position: 60
    - service: cover.set_cover_position
      data:
        entity_id: cover.storen_wohnzimmer_rechts
        position: 40
    - service: cover.set_cover_position
      data:
        entity_id: cover.storen_wohnzimmer_links
        position: 40
    - service: cover.set_cover_position
      data:
        entity_id: cover.storen_kueche_rechts
        position: 40
    - service: cover.set_cover_position
      data:
        entity_id: cover.storen_kueche_links
        position: 40
    - delay:
        seconds: 40
    - service: cover.set_cover_tilt_position
      data:
        entity_id: cover.storen_terrasse_rechts
        position: 75
    - service: cover.set_cover_tilt_position
      data:
        entity_id: cover.storen_terrasse_links
        position: 75
    - service: cover.set_cover_tilt_position
      data:
        entity_id: cover.storen_wohnzimmer_rechts
        position: 75
    - service: cover.set_cover_tilt_position
      data:
        entity_id: cover.storen_wohnzimmer_links
        position: 75
    - service: cover.set_cover_tilt_position
      data:
        entity_id: cover.storen_kueche_rechts
        position: 75
    - service: cover.set_cover_tilt_position
      data:
        entity_id: cover.storen_kueche_links
        position: 75


- alias: 'Storen Wohnzimmer nach Sonne wieder öffnen'
  id: storen_bei_sonne_auf
  trigger:
    platform: numeric_state
    entity_id: sensor.0017d709ae2f48_illumination
    below: 75000
    for:
      minutes: 60
  action:
    - condition: and
      conditions:
        - condition: template
          value_template: "{{ states.sensor.time.state >  (states.input_datetime.storen_ganz_oeffnen.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
        - condition: or
          conditions:
            - condition: template
              value_template: '{{ states.cover.storen_terrasse_links.attributes.current_position < 65 }}'
            - condition: template
              value_template: '{{ states.cover.storen_terrasse_rechts.attributes.current_position < 65 }}'
            - condition: template
              value_template: '{{ states.cover.storen_wohnzimmer_rechts.attributes.current_position < 65 }}'
            - condition: template
              value_template: '{{ states.cover.storen_wohnzimmer_links.attributes.current_position < 65 }}'
            - condition: template
              value_template: '{{ states.cover.storen_kueche_rechts.attributes.current_position < 65 }}'
            - condition: template
              value_template: '{{ states.cover.storen_kueche_links.attributes.current_position < 65 }}'
    - service: cover.open_cover_tilt
      entity_id: cover.storen_terrasse_links
    - service: cover.open_cover_tilt
      entity_id: cover.storen_terrasse_rechts
    - service: cover.open_cover_tilt
      entity_id: cover.storen_wohnzimmer_rechts
    - service: cover.open_cover_tilt
      entity_id: cover.storen_wohnzimmer_links
    - service: cover.open_cover_tilt
      entity_id: cover.storen_kueche_rechts
    - service: cover.open_cover_tilt
      entity_id: cover.storen_kueche_links
    - delay:
        seconds: 10
    - service: cover.open_cover
      entity_id: cover.storen_terrasse_links
    - service: cover.open_cover
      entity_id: cover.storen_terrasse_rechts
    - service: cover.open_cover
      entity_id: cover.storen_wohnzimmer_rechts
    - service: cover.open_cover
      entity_id: cover.storen_wohnzimmer_links
    - service: cover.open_cover
      entity_id: cover.storen_kueche_rechts
    - service: cover.open_cover
      entity_id: cover.storen_kueche_links
