- alias: 'Storen: Wohnzimmer bei Sonne halb schliessen'
  id: storen_bei_sonne_zu
  trigger:
    platform: numeric_state
    entity_id: sensor.0017d709ae2f48_illumination
    above: 9000
    for:
      minutes: 5
  action:
    - condition: and
      conditions:
        - condition: and
          conditions:
            - condition: numeric_state
              entity_id: 'sensor.000ed8a9909c6d_actual_temperature'
              above: 20
            - condition: numeric_state
              entity_id: 'sensor.0017d709ae2f48_illumination'
              above: 8000
        - condition: or
          conditions:
            - condition: template
              value_template: '{{ states.cover.001397099C502F.attributes.current_position > 75 }}'
            - condition: template
              value_template: '{{ states.cover.001397099C5042.attributes.current_position > 75 }}'
            - condition: template
              value_template: '{{ states.cover.001397099C503B.attributes.current_position > 75 }}'
            - condition: template
              value_template: '{{ states.cover.001397099C5046.attributes.current_position > 75 }}'
            - condition: template
              value_template: '{{ states.cover.001397099C5077.attributes.current_position > 75 }}'
            - condition: template
              value_template: '{{ states.cover.001397099C503E.attributes.current_position > 75 }}'
    - service: cover.set_cover_position
      data:
        entity_id: cover.001397099C502F
        position: 60
    - service: cover.set_cover_position
      data:
        entity_id: cover.001397099C5042
        position: 60
    - service: cover.set_cover_position
      data:
        entity_id: cover.001397099C503B
        position: 40
    - service: cover.set_cover_position
      data:
        entity_id: cover.001397099C5046
        position: 40
    - service: cover.set_cover_position
      data:
        entity_id: cover.001397099C5077
        position: 40
    - service: cover.set_cover_position
      data:
        entity_id: cover.001397099C503E
        position: 40
    - delay:
        seconds: 40
    - service: cover.set_cover_tilt_position
      data:
        entity_id: cover.001397099C5042
        position: 75
    - service: cover.set_cover_tilt_position
      data:
        entity_id: cover.001397099C502F
        position: 75
    - service: cover.set_cover_tilt_position
      data:
        entity_id: cover.001397099C503B
        position: 75
    - service: cover.set_cover_tilt_position
      data:
        entity_id: cover.001397099C5046
        position: 75
    - service: cover.set_cover_tilt_position
      data:
        entity_id: cover.001397099C5077
        position: 75
    - service: cover.set_cover_tilt_position
      data:
        entity_id: cover.001397099C503E
        position: 75


- alias: 'Storen: Wohnzimmer nach Sonne wieder öffnen'
  id: storen_bei_sonne_auf
  trigger:
    platform: numeric_state
    entity_id: sensor.0017d709ae2f48_illumination
    below: 5000
    for:
      minutes: 60
  action:
    - condition: and
      conditions:
        - condition: template
          value_template: "{{ states.sensor.time.state >  (states.input_datetime.storen_ganz_oeffnen.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
        - condition: or
          conditions:
            - condition: template
              value_template: '{{ states.cover.001397099C502F.attributes.current_position < 65 }}'
            - condition: template
              value_template: '{{ states.cover.001397099C5042.attributes.current_position < 65 }}'
            - condition: template
              value_template: '{{ states.cover.001397099C503B.attributes.current_position < 65 }}'
            - condition: template
              value_template: '{{ states.cover.001397099C5046.attributes.current_position < 65 }}'
            - condition: template
              value_template: '{{ states.cover.001397099C5077.attributes.current_position < 65 }}'
            - condition: template
              value_template: '{{ states.cover.001397099C503E.attributes.current_position < 65 }}'
    - service: cover.open_cover_tilt
      entity_id: cover.001397099C502F
    - service: cover.open_cover_tilt
      entity_id: cover.001397099C5042
    - service: cover.open_cover_tilt
      entity_id: cover.001397099C503B
    - service: cover.open_cover_tilt
      entity_id: cover.001397099C5046
    - service: cover.open_cover_tilt
      entity_id: cover.001397099C5077
    - service: cover.open_cover_tilt
      entity_id: cover.001397099C503E
    - delay:
        seconds: 10
    - service: cover.open_cover
      entity_id: cover.001397099C502F
    - service: cover.open_cover
      entity_id: cover.001397099C5042
    - service: cover.open_cover
      entity_id: cover.001397099C503B
    - service: cover.open_cover
      entity_id: cover.001397099C5046
    - service: cover.open_cover
      entity_id: cover.001397099C5077
    - service: cover.open_cover
      entity_id: cover.001397099C503E
