- alias: 'Storen: Wohnzimmer nach Sonne wieder öffnen'
  id: storen_bei_sonne_auf
  trigger:
    platform: numeric_state
    entity_id: sensor.klima_garten_illumination
    below: 5000
    for:
      minutes: 60
  action:
    - condition: and
      conditions:
        - condition: template
          value_template: "{{ states.sensor.time.state >  (states.input_datetime.storen_ganz_oeffnen.attributes.timestamp | int | timestamp_custom('%H:%M', false)) }}"
        - condition: or
          conditions:
            - condition: template
              value_template: '{{ state_attr("cover.storen_terrasse_links", "current_position") < 65 }}'
            - condition: template
              value_template: '{{ state_attr("cover.storen_terrasse_rechts", "current_position") < 65 }}'
            - condition: template
              value_template: '{{ state_attr("cover.storen_wohnzimmer_rechts", "current_position") < 65 }}'
            - condition: template
              value_template: '{{ state_attr("cover.storen_wohnzimmer_links", "current_position") < 65 }}'
            - condition: template
              value_template: '{{ state_attr("cover.storen_kueche_rechts", "current_position") < 65 }}'
            - condition: template
              value_template: '{{ state_attr("cover.storen_kueche_links", "current_position") < 65 }}'
    - service: cover.open_cover_tilt
      entity_id: cover.storen_terrasse_links
    - service: cover.open_cover_tilt
      entity_id: cover.storen_terrasse_rechts
    - service: cover.open_cover_tilt
      entity_id: cover.storen_wohnzimmer_rechts
    - service: cover.open_cover_tilt
      entity_id: cover.storen_wohnzimmer_links
    - service: cover.open_cover_tilt
      entity_id: cover.storen_kueche_rechts
    - service: cover.open_cover_tilt
      entity_id: cover.storen_kueche_links
    - delay:
        seconds: 10
    - service: cover.open_cover
      entity_id: cover.storen_terrasse_links
    - service: cover.open_cover
      entity_id: cover.storen_terrasse_rechts
    - service: cover.open_cover
      entity_id: cover.storen_wohnzimmer_rechts
    - service: cover.open_cover
      entity_id: cover.storen_wohnzimmer_links
    - service: cover.open_cover
      entity_id: cover.storen_kueche_rechts
    - service: cover.open_cover
      entity_id: cover.storen_kueche_links
