- alias: 'Storen: Bei Wind öffnen'
  id: storen_bei_wind_oeffnen
  trigger:
    platform: numeric_state
    entity_id: sensor.klima_garten_wind_speed
    above: 70
  action:
    - condition: and
      conditions:
        - condition: or
          conditions:
            - condition: template
              value_template: '{{ state_attr("cover.storen_terrasse_links", "current_position") < 90 }}'
            - condition: template
              value_template: '{{ state_attr("cover.storen_terrasse_rechts", "current_position") < 90 }}'
            - condition: template
              value_template: '{{ state_attr("cover.storen_wohnzimmer_links", "current_position") < 90 }}'
            - condition: template
              value_template: '{{ state_attr("cover.storen_wohnzimmer_rechts", "current_position") < 90 }}'
            - condition: template
              value_template: '{{ state_attr("cover.storen_kueche_links", "current_position") < 90 }}'
            - condition: template
              value_template: '{{ state_attr("cover.storen_kueche_rechts", "current_position") < 90 }}'
            - condition: template
              value_template: '{{ state_attr("cover.storen_schlafzimmer_links", "current_position") < 90 }}'
            - condition: template
              value_template: '{{ state_attr("cover.storen_schlafzimmer_rechts", "current_position") < 90 }}'
    - service: cover.open_cover_tilt
      entity_id:
        - cover.terrasse_rechts
        - cover.terrasse_links
        - cover.wohnzimmer_rechts
        - cover.wohnzimmer_links
        - cover.kuche_rechts
        - cover.kuche_links
        - cover.schlafzimmer_rechts
    - delay:
        seconds: 10
    - service: cover.open_cover
      entity_id:
        - cover.terrasse_rechts
        - cover.terrasse_links
        - cover.wohnzimmer_rechts
        - cover.wohnzimmer_links
        - cover.kuche_rechts
        - cover.kuche_links
        - cover.schlafzimmer_rechts
