- alias: 'Storen: Bei Wind öffnen'
  id: storen_bei_wind_oeffnen
  trigger:
    platform: numeric_state
    entity_id: sensor.0017d709ae2f48_wind_speed
    above: 40.0
  action:
    - condition: and
      conditions:
        - condition: or
          conditions:
            - condition: template
              value_template: '{{ state_attr("cover.001397099c502f", "current_position") < 90 }}'
            - condition: template
              value_template: '{{ state_attr("cover.001397099c5042", "current_position") < 90 }}'
            - condition: template
              value_template: '{{ state_attr("cover.001397099c5046", "current_position") < 90 }}'
            - condition: template
              value_template: '{{ state_attr("cover.001397099c503b", "current_position") < 90 }}'
            - condition: template
              value_template: '{{ state_attr("cover.001397099c503e", "current_position") < 90 }}'
            - condition: template
              value_template: '{{ state_attr("cover.001397099c5077", "current_position") < 90 }}'
            - condition: template
              value_template: '{{ state_attr("cover.001397099c4d22", "current_position") < 90 }}'
            - condition: template
              value_template: '{{ state_attr("cover.001397099c5053", "current_position") < 90 }}'
    - service: cover.open_cover_tilt
      entity_id: cover.schlafzimmer, cover.wohnzimmer
    - delay:
        seconds: 10
    - service: cover.open_cover
      entity_id: cover.schlafzimmer, cover.wohnzimmer
