- alias: 'Storen: Bei Wind öffnen'
  id: storen_bei_wind_oeffnen
  trigger:
    platform: numeric_state
    entity_id: sensor.0017d709ae2f48_wind_speed
    above: 40.0
  action:
    - condition: and
      conditions:
        - condition: or
          conditions:
            - condition: template
              value_template: '{{ states.cover.001397099C502F.attributes.current_position < 90 }}'
            - condition: template
              value_template: '{{ states.cover.001397099C5042.attributes.current_position < 90 }}'
            - condition: template
              value_template: '{{ states.cover.001397099C5046.attributes.current_position < 90 }}'
            - condition: template
              value_template: '{{ states.cover.001397099C503B.attributes.current_position < 90 }}'
            - condition: template
              value_template: '{{ states.cover.001397099C503E.attributes.current_position < 90 }}'
            - condition: template
              value_template: '{{ states.cover.001397099C5077.attributes.current_position < 90 }}'
            - condition: template
              value_template: '{{ states.cover.001397099C4D22.attributes.current_position < 90 }}'
            - condition: template
              value_template: '{{ states.cover.001397099C5053.attributes.current_position < 90 }}'
    - service: cover.open_cover_tilt
      entity_id: cover.schlafzimmer, cover.wohnzimmer
    - delay:
        seconds: 10
    - service: cover.open_cover
      entity_id: cover.schlafzimmer, cover.wohnzimmer