#Trigger and make a picture when movement is detected
- alias: 'Sauron: Bei Bewegung'
  id: sauron_on_movement
  trigger:
    platform: state
    entity_id: binary_sensor.000915699a427d_motion
    to: 'on'
  condition:
    condition: state
    entity_id: device_tracker.74_b5_87_65_1e_ff
    state: 'not_home'
  action:
    service: shell_command.sauron_image


- alias: 'Sauron: Nach Bewegung'
  id: camera_sauron_timed_after_movement
  trigger:
    platform: time_pattern
    minutes: '/1'
  condition:
    condition: and
    conditions:
      - condition: 'state'
        entity_id: binary_sensor.000915699a427d_motion
        state: 'on'
      - condition: state
        entity_id: device_tracker.74_b5_87_65_1e_ff
        state: 'not_home'
  action:
    service: shell_command.sauron_image

- alias: 'Amonsul: Bei Bewegung'
  id: amonsul_on_movement
  trigger:
    platform: state
    entity_id: binary_sensor.000915699a427d_motion
    to: 'on'
  condition:
    condition: state
    entity_id: device_tracker.74_b5_87_65_1e_ff
    state: 'not_home'
  action:
    service: shell_command.amonsul_image


- alias: 'Amonsul: Nach Bewegung'
  id: camera_amonsul_timed_after_movement
  trigger:
    platform: time_pattern
    minutes: '/1'
  condition:
    condition: and
    conditions:
      - condition: 'state'
        entity_id: binary_sensor.000915699a427d_motion
        state: 'on'
      - condition: state
        entity_id: device_tracker.74_b5_87_65_1e_ff
        state: 'not_home'
  action:
    service: shell_command.amonsul_image
