#trigger every 10 min or every 30s when movement
- alias: 'Sauron: Is watching'
  id: camera_sauron_timed
  trigger:
    platform: time_pattern
    minutes: '/10'
  condition:
    condition: state
    entity_id: device_tracker.iphonexr
    state: 'not_home'
  action:
    service: shell_command.sauron_image

#trigger every 10 min or every 30s when movement
- alias: 'Amonsul: Is watching'
  id: camera_amonsul_timed
  trigger:
    platform: time_pattern
    minutes: '/10'
  condition:
    condition: state
    entity_id: device_tracker.iphonexr
    state: 'not_home'
  action:
    service: shell_command.amonsul_image

#trigger every 60 min
- alias: 'Radagast: Is watching'
  id: camera_radagast_timed
  trigger:
    platform: time_pattern
    minutes: '0'
  action:
    service: shell_command.radagast_image
