- alias: 'Meldung: Bewegung'
  id: meldung_bewegung
  trigger:
    platform: state
    entity_id: binary_sensor.bewegung_wohnzimmer_motion
    from: "off"
    to: "on"
  condition:
    not:
      - condition: state
        entity_id: person.alex
        state: 'home'
      - condition: state
        entity_id: person.minna
        state: 'home'
      - condition: state
        entity_id: person.durin
        state: 'home'
      - condition: state
        entity_id: person.nuri
        state: 'home'
  action:
    - service: script.notify_rp
      data:
        title: 'Bewegung erkannt'
        message: 'Bewegung erkannt'
