- alias: 'Meldung: Subject fire!!'
  id: meldung_feuer
  trigger:
    - platform: state
      entity_id: sensor.rauchmelder_reduit_smoke_detector_alarm_status
      from: "on"
      to: "off"
    - platform: state
      entity_id: sensor.rauchmelder_reduit_smoke_detector_alarm_status
      from: "off"
      to: "on"
    - platform: state
      entity_id: sensor.rauchmelder_wohnzimmer_smoke_detector_alarm_status
      from: "on"
      to: "off"
    - platform: state
      entity_id: sensor.rauchmelder_wohnzimmer_smoke_detector_alarm_status
      from: "off"
      to: "on"
  action:
    - service: script.notify_rp
      data:
        title: 'ES BRENNT'
        message: >
          ES BRENNT! Schau auf der cam nach!
