- alias: 'Meldung: Fenster/Tür offen gelassen'
  id: meldung_offen_gelassen
  trigger:
    platform: state
    entity_id: binary_sensor.tur_haustur_state
    from: "off"
    to: "on"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: person.alex
        state: 'home'
      - condition: or
        conditions:
          - condition: state
            entity_id: binary_sensor.fenster
            state: 'on'
          - condition: state
            entity_id: binary_sensor.tur_terrasse_state
            state: 'on'
  action:
    - service: script.notify_rp
      data:
        title: 'Es ist noch was offen!'
        message: >
          Türen Zustand geändert:

          {% for entity_id in states.binary_sensor.tueren.attributes.entity_id %}
          {% set domain, device = entity_id.split('.') %}
          {{ states[domain][device].attributes.friendly_name }} : {{ states[domain][device].state }}
          {% endfor %}
          {% for entity_id in states.binary_sensor.fenster.attributes.entity_id %}
          {% set domain, device = entity_id.split('.') %}
          {{ states[domain][device].attributes.friendly_name }} : {{ states[domain][device].state }}
          {% endfor %}
