- alias: 'Meldung: Thuja hat zu wenig Wasser'
  id: thuja_water_low
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: sensor.thuja2_moisture
    below: 10
    for:
      hours: 1
  action:
    - service: script.notify_rp
      data:
        title: 'Giess mich!'
        message: 'Die Thujas brauchen Wasser!'
