- alias: 'Meldung: Türen offen'
  id: meldung_türen_offen
  trigger: 
    platform: state
    entity_id: binary_sensor.tur_haustur_state
  condition:
    condition: state
    entity_id: person.alex
    state: 'not_home'
  action:
    - service: script.notify_rp
      data: 
        title: 'Türen Zustand'
        message: >
          Türen Zustand geändert: Haustür
          {{ states['binary_sensor']['tur_haustur_state'].state }}
