- alias: 'Meldung: Türen offen'
  id: meldung_türen_offen
  trigger: 
    platform: state
    entity_id: group.tueren
  condition:
    condition: state
    entity_id: device_tracker.iphonexr
    state: 'not_home'
  action:
    - service: script.notify_rp
      data: 
        title: 'Türen Zustand'
        message: >
          Türen Zustand geändert:

          {% for entity_id in states.group.tueren.attributes.entity_id %}
          {% set domain, device = entity_id.split('.') %}
          {{ states[domain][device].attributes.friendly_name }} : {{ states[domain][device].state }}

          {% endfor %}
