- alias: 'Meldung: Wind'
  id: meldung_wind
  trigger:
    platform: numeric_state
    entity_id: sensor.klima_garten_wind_speed
    above: 40.0
  condition:
    condition: state
    entity_id: person.alex
    state: 'not_home'
  action:
    - service: script.notify_rp
      data:
        title: 'STURM INC'
        message: >
          Ich hoffe, du hast alles festgemacht!!
