- alias: 'Gollum: Saug den Staub'
  id: saug_den_staub
  trigger:
    platform: time
    at: '10:00:00'
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - tue
          - fri
  action:
    - service: vacuum.start
      entity_id: vacuum.gollum
    - service: automation.turn_on
      entity_id: automation.gollum_notify_ran

- alias: 'Gollum: Staubbehälter leeren'
  id: staubbehaelter_leeren
  trigger:
    platform: state
    entity_id: binary_sensor.0000d8a991d35c_state
  action:
    - service: script.notify_rp
      data:
        title: 'Gollum ist voll'
        message: >
          Gollum war fleissig, nimm ihm bitte den Ring ab.
