- alias: 'Brunnen: Bei trockener Luft einschalten'
  id: brunnen_auto_on
  trigger: 
    platform: numeric_state
    entity_id: sensor.000ed8a9909c6f_humidity
    below: 45
  condition:
    condition: 'state'
    entity_id: switch.meq1478516
    state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.meq1478516
    - service: script.notify_rp
      data: 
        title: Brunnen
        message: Wohnzimmer zu trocken, Brunnen wird eingeschaltet.

- alias: 'Brunnen: Bei feuchter Luft ausschalten'
  id: brunnen_auto_off
  trigger:
    platform: numeric_state
    entity_id: sensor.000ed8a9909c6f_humidity
    above: 48
  condition:
    condition: 'state'
    entity_id: switch.meq1478516
    state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.meq1478516
    - service: script.notify_rp
      data:
        title: Brunnen
        message: Wohnzimmer wieder feucht genug, Brunnen wird ausgeschaltet.

