- alias: 'Strom: Schreibtisch aus nach 5min >40W'
  id: strom_schreibtisch_auto_off_5min
  trigger: 
    platform: numeric_state
    entity_id: sensor.strom_schreibtisch_power
    below: 30
    for:
      minutes: 5
  action:
    service: switch.turn_off
    data:
      entity_id: switch.strom_schreibtisch
