- alias: Update Grau3 device tracker
  trigger:
    - platform: state
      entity_id: sensor.trackit_grau3_location
      attribute: timestamp
  action:
    - service: device_tracker.see
      data:
        dev_id: "Grau3"
        gps:
          - "{{ state_attr('sensor.trackit_grau3_location','latitude') }}"
          - "{{ state_attr('sensor.trackit_grau3_location','longitude') }}"
        gps_accuracy: "{{ state_attr('sensor.trackit_grau3_location','accuracy') }}"
