- alias: Update Grau1 device tracker
  trigger:
    - platform: state
      entity_id: sensor.trackit_grau1_location
      attribute: timestamp
  action:
    - service: device_tracker.see
      data:
        dev_id: "Grau1"
        gps:
          - "{{ state_attr('sensor.trackit_grau1_location','latitude') }}"
          - "{{ state_attr('sensor.trackit_grau1_location','longitude') }}"
        gps_accuracy: "{{ state_attr('sensor.trackit_grau1_location','accuracy') }}"
