- alias: "Schalter - Küche"
  trigger:
    platform: event
    event_type: homematic.keypress
    event_data:
      name: schalter_wohnzimmer
      subtype: 1
      type: press_short
  action:
    service: switch.toggle
    entity_id: switch.licht_kueche
- alias: "Schalter - Wohzimmerlicht"
  trigger:
    platform: event
    event_type: homematic.keypress
    event_data:
      name: schalter_wohnzimmer
      subtype: 2
      type: press_short
  action:
    service: light.toggle
    entity_id: light.wohnzimmer_licht_2
- alias: "Schalter - Storen runter Wohnzimmer"
  trigger:
    platform: event
    event_type: homematic.keypress
    event_data:
      name: schalter_wohnzimmer
      subtype: 3
      type: press_short
  action:
    service: cover.close_cover
    entity_id: cover.wohnzimmer
- alias: "Schalter - Storen zu Wohnzimmer"
  trigger:
    platform: event
    event_type: homematic.keypress
    event_data:
      name: schalter_wohnzimmer
      subtype: 3
      type: press_long
  action:
    service: cover.close_cover_tilt
    entity_id: cover.wohnzimmer
- alias: "Schalter - Storen hoch Wohnzimmer"
  trigger:
    platform: event
    event_type: homematic.keypress
    event_data:
      name: schalter_wohnzimmer
      subtype: 4
      type: press_short
  action:
    service: cover.open_cover
    entity_id: cover.wohnzimmer
- alias: "Schalter - Storen auf Wohnzimmer"
  trigger:
    platform: event
    event_type: homematic.keypress
    event_data:
      name: schalter_wohnzimmer
      subtype: 4
      type: press_long
  action:
    service: cover.open_cover_tilt
    entity_id: cover.wohnzimmer
