- alias: 'Licht aus wenn raus'
  id: licht_aus_wenn_raus
  trigger: 
    platform: state
    entity_id: device_tracker.iphonexr
    from: 'home'
    to: 'not_home'
    for:
      hours: 0
      minutes: 10
      seconds: 0
  action:
    service: homeassistant.turn_off
    data_template: 
      entity_id: group.licht
