- alias: 'Licht aus wenn raus'
  id: licht_aus_wenn_raus
  trigger: 
    platform: state
    entity_id: device_tracker.iphonexr
    from: 'home'
    to: 'not_home'
    for:
      hours: 1
      minutes: 0
      seconds: 0
  action:
    service: light.turn_off
    data_template: 
      entity_id: group.all_lights
