- alias: 'Licht: Lichterkette abends an'
  id: lichterkette_abends
  trigger:
    platform: sun
    event: sunset
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.001015699eaa6b

- alias: 'Licht: Lichterkette nachts aus'
  id: lichterkette_morgens
  trigger:
    platform: time
    at: "23:00:00"
  condition:
    - condition: 'state'
      entity_id: switch.001015699eaa6b
      state: 'on'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.001015699eaa6b

- alias: 'Licht: Lichterkette morgens aus'
  id: lichterkette_abends
  trigger:
    platform: sun
    event: sunrise
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.001015699eaa6b

- alias: 'Licht: Lichterkette morgens an'
  id: lichterkette_morgens
  trigger:
    platform: time
    at: "05:00:00"
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.001015699eaa6b
